---
- name: web-server deinstallation
  hosts: nodes
  tasks:
  - name: disable service
    service: 
      name: httpd
      state: stopped   
      enabled: no
  - name: deinstall httpd package
    yum:
      name: httpd
      state: absent
  - name: delete index file
    file:
      path: /var/www/html/index.html
      state: absent
  - name: close port in firewall
    firewalld:
      service: http
      permanent: true
      state: disabled
      immediate: yes

